name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc tên nhánh bạn đang sử dụng

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # hoặc phiên bản Node.js bạn muốn

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # nếu bạn có bước build, nếu không có thì có thể bỏ qua

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
