name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc tên nhánh mà bạn đang sử dụng

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Đường dẫn chứa tệp HTML của bạn
          publish_branch: gh-pages  # Nhánh đích để đẩy
